### ISSUE TITLE
Refactor jsOptions in c-slider.hbs

### ISSUE THREAD

**Issue by andy-gutsche** [Veams/component-slider#1]
change {{options.jsKey}} and {{options.jsValue}} to {{jsKey}} and {{jsValue}} and add jsObject like in {{c-cta}}

**Comment by Sebastian-Fitzner** [comment]
No, just 
[ ] change {{options.jsKey}} and {{options.jsValue}} to {{jsKey}} and {{jsValue}} and 
[ ] add jsObject like in {{c-cta}}
