### ISSUE TITLE
Add option for triggering click event if touch swipe is enabled

### ISSUE THREAD

**Issue by andy-gutsche** [Veams/component-slider#4]
triggerTouchSwipeClick: false

**Comment by Sebastian-Fitzner** [comment]
It's already included. Just add the class `.isnt-swipable` onto the clickable element.

**Comment by Sebastian-Fitzner** [comment]
I guess you just want to enable click events in the slider if swipe is enabled, right?!

**Comment by andy-gutsche** [comment]
Exactly! It can be done inside click function of jquery touch swipe. I've already added the necessary code to the slider in my recent project. Just wanted to merge it back into original veams-component-slider ;-)
